project:
  type: website
  output-dir: docs
website:
  title: "Julien Lalanne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/papers.qmd
        text: Publications
      # - href: pages/news.qmd
      #   text: News
      - href: pages/curriculum.qmd
        text: Curriculum
      # - href: pages/teaching.qmd
      #   text: Teaching
      - href: pages/contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
      
    css: styles.css
    toc: false



